Fixed not refreshed when create file or folder and delete
Natizyskunk/vscode-sftp pull request #159
Opened 2022-05-11 03:00 UTC by dmdlzaaa

Fixed:
- Remote Explorer Not refreshed when create file or folder and delete.
- "Create Folder" is not visible when right-clicking on a Remote Explorer folder.
- "Create Folder" is visible when right-clicking on a Remote Explorer file.

2022-05-11 03:01 UTC, dmdlzaaa commented
#134

2022-09-23 18:21 UTC, Natizyskunk commented
Related issues : #47, #122, #134

2022-09-26 15:35 UTC, Natizyskunk commented
@NyaPPuu Please perge develop in your branhc and update your pull-request :)

2022-09-27 01:23 UTC, NyaPPuu commented
> @NyaPPuu Please merge develop in your branch and update your pull-request :)

Updated all 3 pull requests.
An error occurred in the dependabot.yml file and I temporarily deleted it.

I'm not familiar with using GitHub yet, so please let me know if there are any mistakes.
Thank you.

2022-09-27 11:57 UTC, Natizyskunk commented
@NyaPPuu,
I'm not able to merge your request. It seems that ou still have some conflict with the dependabot.yml file.
Please be sure to be up-to-date with the latest develop branch and then push to the develop branch :)

2022-09-27 12:29 UTC, NyaPPuu commented
> That's not a big deal but FYI you should never delete a file if you don't know what it does in particular for files that are inside the `.github/` folder because they're files that run some specific actions at push event.
> 
> Also I'm not able to merge your request. It seems that ou still have some conflict with the dependabot.yml file. Please be sure to be up-to-date with the latest develop branch and then push to the develop branch :)

Thanks I'm learning a lot about github.
I will continue to contribute by coding hard in the future.

2022-09-27 12:35 UTC, Natizyskunk commented
@NyaPPuu,
Perfect, just don't forget to check my reviews so I can merge all your work 😉

2022-10-05 08:30 UTC, NyaPPuu commented
@Natizyskunk 
I found out that the workaround for PR #159 refreshes the entire root when a file is created or deleted.
ex) If you create a new file in folder 'A', folder 'B' will also be refreshed.
![image](https://user-images.githubusercontent.com/1353557/194016032-f524c5c7-4815-4477-9fb7-5aa49841dc38.png)

The `src/modules/remoteExplorer/treeDataProvider.ts` file from PR #220 is required to correct this issue
I want to merge PR #220 with PR #159.
Is that ok?

2022-10-19 00:47 UTC, NyaPPuu commented
I cleaned up my commit
And merge with #220

2022-10-23 23:38 UTC, Natizyskunk reviewed
Please make the requested changes please 🙂

2022-10-23 23:39 UTC, Natizyskunk requested changes
Please make the requested changes please 🙂

2022-10-23 23:44 UTC, Natizyskunk commented
@NyaPPuu,
Also keep in mind to always be up-to-date with the `develop` branch.

2022-10-24 08:57 UTC, NyaPPuu commented
I pulled `develop` branch to this `fix_refresh` branch.
![image](https://user-images.githubusercontent.com/1353557/197488120-6788a034-0f67-4738-b055-043c283d12e2.png)

But `Files changed` tab seems to show old CHANGELOG.md files, why?

2022-10-24 08:59 UTC, NyaPPuu reviewed
Review finished.

2022-10-29 02:35 UTC, Natizyskunk commented on package.json
> +          "when": "view == remoteExplorer && viewItem != file"
ok, perfect.

2022-10-29 02:41 UTC, Natizyskunk approved these changes
Perfect ! 🙂

2022-10-29 03:02 UTC, Natizyskunk approved these changes

2022-10-29 03:54 UTC, merged

2022-10-29 03:55 UTC, Natizyskunk commented
It's been merged in #243 😉