Cleanup Text in Markdown Files
Natizyskunk/vscode-sftp pull request #213
Opened 2022-09-30 18:19 UTC by BrayFlex

- Enforced formatting consistency where overlooked
- Improved the language used
- Fixed some spelling mistakes
- Rewrote the project description

Its not much but this project is awesome and I wanted to contribute to the work done.

2022-10-13 15:13 UTC, Natizyskunk commented
@BrayFlex,
Thanks a lot for your contribution.
Please correct my reviews this way I can merge your work 🙂

2022-10-13 15:41 UTC, BrayFlex commented
> @BrayFlex, Thanks a lot for your contribution. Please correct my reviews this way I can merge your work 🙂

I don't think you're review went through

2022-10-23 04:31 UTC, Natizyskunk commented
@BrayFlex,

Don't you see those reviews ?
![image](https://user-images.githubusercontent.com/59120131/197373820-4e0c8d74-5769-4c46-a713-aa710f4ab711.png)

2022-10-23 05:02 UTC, BrayFlex commented
> @BrayFlex,
> 
> Don't you see those reviews ? ![image](https://user-images.githubusercontent.com/59120131/197373820-4e0c8d74-5769-4c46-a713-aa710f4ab711.png)

Am I looking in the wrong play @Natizyskunk ? 
![image](https://user-images.githubusercontent.com/33260515/197374788-4b9e6c4d-f2b9-43c6-bf71-a69cac53178e.png)

2022-10-23 23:33 UTC, Natizyskunk commented
@BrayFlex,
If you can't so them in the "conversation" tab, you should be able to see them in the "Files changed" tab.
Please let me now if you can't see them.

2022-10-23 23:34 UTC, Natizyskunk reviewed
Please make the requested changes please 🙂

2022-10-23 23:35 UTC, BrayFlex commented
> @BrayFlex, If you can't so them in the "conversation" tab, you should be able to see them in the "Files changed" tab. Please let me now if you can't see them.

@Natizyskunk Unfortunately there are no comments

2022-10-23 23:36 UTC, Natizyskunk commented
> > @BrayFlex,
> > Don't you see those reviews ?
> 
> Am I looking in the wrong place @Natizyskunk ? ![image](https://user-images.githubusercontent.com/33260515/197374788-4b9e6c4d-f2b9-43c6-bf71-a69cac53178e.png)

@BrayFlex,
My bad I had forgotten to do something on my end to make it visible for you.
You should now be able to see them in the "conversation" tab. If not you should also be able to see them in the "Files changed" tab.

2022-10-23 23:38 UTC, BrayFlex commented
> > > @BrayFlex,
> > > Don't you see those reviews ?
> > 
> > 
> > Am I looking in the wrong place @Natizyskunk ? ![image](https://user-images.githubusercontent.com/33260515/197374788-4b9e6c4d-f2b9-43c6-bf71-a69cac53178e.png)
> 
> @BrayFlex, My bad I had forgotten to do something on my end to make it visible for you. You should now be able to see them in the "conversation" tab. If not you should also be able to see them in the "Files changed" tab.

I see it now, will fix these up soon!

2022-10-23 23:41 UTC, Natizyskunk requested changes
Please make the requested changes please 🙂

2022-10-23 23:41 UTC, Natizyskunk commented
> > > @BrayFlex,
> > > Don't you see those reviews ?
> > 
> > 
> > Am I looking in the wrong place @Natizyskunk ? ![image](https://user-images.githubusercontent.com/33260515/197374788-4b9e6c4d-f2b9-43c6-bf71-a69cac53178e.png)
> 
> @BrayFlex, My bad I had forgotten to do something on my end to make it visible for you. You should now be able to see them in the "conversation" tab. If not you should also be able to see them in the "Files changed" tab.

Perfect 😀

2022-10-23 23:44 UTC, Natizyskunk commented
@BrayFlex,
Also keep in mind to always be up-to-date with the `develop` branch.

2022-10-24 00:19 UTC, BrayFlex commented on README.md
> +Edit the configuration parameters to your remote server
I wouldn't say so, you would not say: "Enter your matching login credentials", you'd just say "Enter your login credentials"

2022-10-24 00:23 UTC, BrayFlex commented on README.md
> +5. Done - you can now edit locally and after each save it will upload to sync your remote file with the local copy.
Did you mean continue with 4?

2022-10-28 05:12 UTC, Natizyskunk commented on README.md
> +Edit the configuration parameters to your remote server
@BrayFlex,
For me "Edit the configuration parameters with your remote server informations" would be a nice in-between just to make it clear for users about what they should do. Is it ok for you ?

2022-10-28 05:20 UTC, Natizyskunk commented on README.md
> +5. Done - you can now edit locally and after each save it will upload to sync your remote file with the local copy.
@BrayFlex,
Yes, my bad.

should look like that : 
```md
1. In `VS Code`, open a local directory you wish to sync to the remote server (or create an empty directory .
2. `Ctrl+Shift+P` on Windows/Linux or `Cmd+Shift+P` on Mac open command palette, run `SFTP: config` command.
3. A basic configuration file will appear named `sftp.json` under the `.vscode` directory.
[...]
4. Save and close the `sftp.json` file.
5. `Ctrl+Shift+P` on Windows/Linux or `Cmd+Shift+P` on Mac open command palette.
[...]
```

2022-10-28 05:26 UTC, Natizyskunk requested changes
Just some minor changes and we should be good to go.

2022-10-28 05:26 UTC, Natizyskunk commented on README.md
> +6. Voilà!
@BrayFlex,
Please leave the punctuation at the end of each sentence.

2022-10-28 05:26 UTC, Natizyskunk commented on README.md
> +4. Voilà!
@BrayFlex,
Please leave the punctuation at the end of each sentence.

2022-10-28 12:36 UTC, BrayFlex commented on README.md
> +Edit the configuration parameters to your remote server
I think that works too

2022-10-28 12:45 UTC, BrayFlex commented
@Natizyskunk I think that about fixes everything

2022-10-29 02:32 UTC, Natizyskunk approved these changes
Perfect ! 🙂

2022-10-29 03:02 UTC, Natizyskunk approved these changes

2022-10-29 04:00 UTC, merged

2022-10-29 04:01 UTC, Natizyskunk commented
It's been merged in #244 😉